///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String assetsQuranIMG = 'assets/quranIMG.png';
  static const String backgroundHadithBG = 'assets/background/hadithBG.png';
  static const String backgroundQuranBG = 'assets/background/quranBG.png';
  static const String backgroundRadioBG = 'assets/background/RadioBG.png';
  static const String backgroundSbhaBG = 'assets/background/sbhaBG.png';
  static const String backgroundSouraDetailsBG = 'assets/background/SouraDetailsBG.png';
  static const String backgroundTimesBG = 'assets/background/timesBG.png';

  static const String iconsHadith = 'assets/icons/hadith.png';
  static const String iconsQuran = 'assets/icons/quran.png';
  static const String iconsRadio = 'assets/icons/radio.png';
  static const String iconsSebha = 'assets/icons/sebha.png';
  static const String iconsSuraNumIcn = 'assets/icons/suraNumIcn.png';
  static const String iconsTime = 'assets/icons/time.png';
  static const String onboardingIconsBearish = 'assets/onboarding_icons/bearish.png';
  static const String onboardingIconsKabba = 'assets/onboarding_icons/kabba.png';
  static const String onboardingIconsRadio = 'assets/onboarding_icons/radio.png';
  static const String onboardingIconsReading = 'assets/onboarding_icons/reading.png';
  static const String onboardingIconsWelcome = 'assets/onboarding_icons/welcome.png';
  static const String splashIslami = 'assets/splash/Islami.png';
  static const String splashIslamiLogo = 'assets/splash/islamiLogo.png';
  static const String splashLeftShape = 'assets/splash/leftShape.png';
  static const String splashMosque = 'assets/splash/Mosque.png';
  static const String splashRightShape = 'assets/splash/rightShape.png';
  static const String splashRouteBranding = 'assets/splash/routeBranding.png';
  static const String splashSplashBackground = 'assets/splash/splashBackground.png';
  static const String splashTopRightShape = 'assets/splash/topRightShape.png';
}
